# Generated by Django 3.0.6 on 2022-07-15 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Product')),
            ],
        ),
    ]
