# Generated by Django 3.0.6 on 2022-07-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='item_count',
            field=models.IntegerField(default=0),
        ),
    ]
